name: Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create plugin zip
        run: |
          cd plugin.video.nextgenrt
          zip -r ../plugin.video.nextgenrt-${{ steps.get_version.outputs.VERSION }}.zip .
          cd ..
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: plugin.video.nextgenrt-${{ steps.get_version.outputs.VERSION }}.zip
          body: |
            ## NextGen RT News v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            1. Download the `plugin.video.nextgenrt-${{ steps.get_version.outputs.VERSION }}.zip` file below
            2. In Kodi, go to Settings → Add-ons → Install from zip file
            3. Select the downloaded zip file
            4. The plugin will automatically install InputStream Adaptive if needed
            
            ### What's Changed
            See the [README](https://github.com/poslogica/plugin.video.nextgenrt/blob/main/README.md) for full details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
